#NGINX.conf example.2
events {
    worker_connections 1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;


        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri.html $uri/ /index.html;
        }
    }
}
